services:
  neko:
    build: .
    restart: unless-stopped
    shm_size: 2gb
    cap_add:
      - SYS_ADMIN
    ports:
      - '8080:8080'
      - '9223:9223'
      - '52000-52100:52000-52100/udp'
    volumes:
      # Persistent browser profile storage (custom location)
      - "${NEKO_PROFILE:-/root/sessions/chrome-profile}:/home/neko/chrome-profile"
    environment:
      NEKO_DESKTOP_SCREEN: ${NEKO_DESKTOP_SCREEN:-1920x1080@30}
      NEKO_MEMBER_MULTIUSER_USER_PASSWORD: ${NEKO_MEMBER_MULTIUSER_USER_PASSWORD:-neko}
      NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD: ${NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD:-admin}
      NEKO_WEBRTC_EPR: ${NEKO_WEBRTC_EPR:-52000-52100}
      NEKO_WEBRTC_ICELITE: ${NEKO_WEBRTC_ICELITE:-1}
      NEKO_DESKTOP_UNMINIMIZE: true
      NEKO_DESKTOP_UPLOAD_DROP: true
      NEKO_DESKTOP_FILE_CHOOSER_DIALOG: false
      NEKO_MEMBER_PROVIDER: ${NEKO_MEMBER_PROVIDER:-noauth}